"""empty message

Revision ID: 0efcac430d0d
Revises: f275777c19a8
Create Date: 2024-03-12 17:08:07.168762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efcac430d0d'
down_revision = 'f275777c19a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('distance')
        batch_op.drop_column('speed')

    # ### end Alembic commands ###
