"""empty message

Revision ID: 0f8f6f8cc632
Revises: efad39583bf8
Create Date: 2024-03-13 18:43:02.914937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8f6f8cc632'
down_revision = 'efad39583bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_expiry', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('payment_expiry')

    # ### end Alembic commands ###
