"""empty message

Revision ID: 201e7f096f2d
Revises: f0dc2174d85b
Create Date: 2024-02-29 16:15:46.246179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201e7f096f2d'
down_revision = 'f0dc2174d85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=40), nullable=True))
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.VARCHAR(length=2), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
