"""empty message

Revision ID: 8c84c4b4a54b
Revises: 201e7f096f2d
Create Date: 2024-03-06 18:15:11.752111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c84c4b4a54b'
down_revision = '201e7f096f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpx_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.String(length=1000000000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpx_routes')
    # ### end Alembic commands ###
