"""empty message

Revision ID: b8ec064b573e
Revises: 8c84c4b4a54b
Create Date: 2024-03-08 12:09:45.596358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ec064b573e'
down_revision = '8c84c4b4a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', sa.Text(), nullable=True))
        batch_op.drop_column('geojson')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geojson', sa.VARCHAR(length=1000000000), nullable=True))
        batch_op.drop_column('geom')

    # ### end Alembic commands ###
