"""empty message

Revision ID: d174e76977a3
Revises: f83b79e75842
Create Date: 2024-03-12 17:22:20.148838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd174e76977a3'
down_revision = 'f83b79e75842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=25),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
