"""empty message

Revision ID: efad39583bf8
Revises: d174e76977a3
Create Date: 2024-03-13 17:51:19.936411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad39583bf8'
down_revision = 'd174e76977a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_4_digits', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('last_4_digits')

    # ### end Alembic commands ###
