"""empty message

Revision ID: f275777c19a8
Revises: b8ec064b573e
Create Date: 2024-03-08 12:11:49.685277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f275777c19a8'
down_revision = 'b8ec064b573e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geojson', sa.Text(), nullable=True))
        batch_op.drop_column('geom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', sa.TEXT(), nullable=True))
        batch_op.drop_column('geojson')

    # ### end Alembic commands ###
