"""empty message

Revision ID: f8083ff446ab
Revises: 0f8f6f8cc632
Create Date: 2024-03-14 15:25:42.270923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8083ff446ab'
down_revision = '0f8f6f8cc632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
