"""empty message

Revision ID: f83b79e75842
Revises: 0efcac430d0d
Create Date: 2024-03-12 17:16:15.080339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83b79e75842'
down_revision = '0efcac430d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx_routes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Float(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
